const Metadatas = {
    DESERIALIZERS: 'METADATA_DESERIALIZERS',
    DIRECTORY_NAME: 'DIRECTORY_NAME',
    DIRECTORY_PATH: 'DIRECTORY_PATH',
    COMMAND_PARSERS: 'METADATA_COMMAND_PARSERS',
    COMMANDS: 'METADATA_COMMANDS',
    CREATOR_CHAIN: 'METADATA_CREATOR_CHAIN',
    CREATORS: 'METADATA_CREATORS',
    GLOBAL_CONTEXT: 'METADATA_GLOBAL_CONTEXT',
    OPTIONS: 'METADATA_OPTIONS',
    SERIALIZERS: 'METADTA_SERIALIZERS'
};

export default Metadatas;